site_name: Twitch Recover Documentation
copyright: Copyright &copy; 2022 Twitch Recover

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - search.highlight
    - search.share
plugins:
  - search
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
